# -*- encoding : utf-8 -*-
development:
  host: localhost
  database: wat_development

test:
  host: localhost
  database: wat_test

# set these environment variables on your prod server
production:
  host: localhost
  database: wat_development
